name: Deploy to AWS
on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
        # You'll need to add the corresponding public key to your AWS server's authorized_keys files

    - name: Deploy to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/ ubuntu@3.110.204.242 "
        cd /var/www/html/ecom
        sudo git add .
        sudo git commit -m "servercommit"
        sudo git pull origin master 
        sudo systemctl restart nginx"
